### ISSUE TITLE
Problems with crafting a Thirst Quencher 

### ISSUE THREAD

**Issue by Wishmaster3** [p455w0rd/ToughExpansion#11]
When I try to add the ingredients to a workbench, JEI complains about a missing bottle of water.

![1](https://user-images.githubusercontent.com/3602044/28932770-e9364406-787a-11e7-88e0-d941b8a2094a.jpg)

The recipe shows a Bottle with Temperature: 300K but the Bottle in my inventory doesn't have a temerature.

![2](https://user-images.githubusercontent.com/3602044/28932835-2eb3b252-787b-11e7-89da-323c127b1a19.jpg)

While JEI does NOT complain about the full canteen in my inventory, it took me two days to find out that I don't have to heat up the waterbottle but need to use a empty canteen :/ . When I add the right ingredients manually to a crafting grid, it crafts the Thirst Quencher.
I'm not sure what exactly the problem is and wether your mod or any other mod causes this behavior, but just to let you know...
Anyways, nice mod! 

Version is MC 1.10.2 with Forge 12.18.3.2316

**Comment by Nightcaste** [comment]
While the item is from Tough Expansion, everything you have indicated here is due to JEI.  The canteen has no "durability" bar, so that's an empty.  The water temperature thing is, I believe, from Tinkers' Construct.

Just so you know, 300K is 300 Kelvin, which is equal to about 27 degrees C, or about 80 degrees F, AKA room temperature.

**Comment by p455w0rd** [comment]
So I was unaware that WATER is actually considered a potion type. Will be fixed in next update. Thanks for the report!
