### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by 0Navis0** [p455w0rd/ToughExpansion#25]
I thought hunger quencher could be added, it would work as thrist quencher but with food, it would be pretty useful. I thought air conditionning unit and heating unit should come back. It was pretty useful for automating for warming or refreshing the temperature. It adds more varient of different machines, and make the progression for getting the temperature regulator better. The different machines should have a gui too.

**Comment by p455w0rd** [comment]
Hunger Quencher is out of the scope of this mod. It's purely an addon for Tough As Nails. Air Conditioner and Heater were removed due to bugs in TAN. I'm sorry but I can't grant any of these requests. I do have an update waiting to go live, I just have to get around to testing with the latest TAN first. If you want a powered hunger item, request for it to be added to MorphTweaks https://github.com/p455w0rd/MorphTweaks and I'll see what I can do :)

**Comment by 0Navis0** [comment]
Oh ok, and what was the bug with air conditionner and heater ? It's sad you had to remove them, they were nice feature. :(
